# Generated by Django 3.2.5 on 2022-07-06 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='historyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('is_phishing', models.BooleanField(null=True)),
                ('screenshot', models.ImageField(null=True, upload_to='media/images/')),
                ('whois_detail', models.CharField(max_length=250, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
