# Generated by Django 3.2.5 on 2022-07-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymodel',
            name='screenshot',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
