# Generated by Django 3.2.5 on 2022-07-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0010_auto_20220706_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
            ],
        ),
    ]
