# Generated by Django 3.2.5 on 2022-07-06 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0011_reportmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportmodel',
            old_name='url',
            new_name='url_report',
        ),
    ]
