# Generated by Django 3.2.5 on 2022-07-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0012_rename_url_reportmodel_url_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='whois_address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historymodel',
            name='whois_city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historymodel',
            name='whois_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historymodel',
            name='whois_ns',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historymodel',
            name='whois_org',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
