# Generated by Django 3.2.5 on 2022-07-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0013_auto_20220710_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='whois_crt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='historymodel',
            name='whois_exp',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
